--- 
Resources: 
  - 
    TargetService: 
      Properties: 
        LoadBalancerInfo: 
          ContainerName: dsapi
          ContainerPort: 5000
        TaskDefinition: "arn:aws:ecs:ap-southeast-1:361421599476:task-definition/datascience-api-prod-taskdef:2"
      Type: "AWS::ECS::Service"
files: 
  - 
    destination: /usr/local/codedeployresources
    source: /dsapi
hooks: 
  AfterInstall: 
    - 
      location: scripts/staging/pull_staging_image.sh
      runas: ec2-user
      timeout: 60
  ApplicationStart: 
    - 
      location: scripts/staging/start_staging_container.sh
      runas: ec2-user
      timeout: 10
  ApplicationStop: 
    - 
      location: scripts/kill_container.sh
      runas: ec2-user
      timeout: 20
os: linux
version: 0.1
